### ISSUE TITLE
Displaying statistics file name

### ISSUE THREAD

**Issue by stephaneguindon** [tgvaughan/icylog#4]
Would it be possible to add the log file name somewhere (e.g., in the upper right corner of the dashboard)? I have several tabs with icylog running and sometimes can't remember which trace corresponds to which log file. Having the name of this file displayed somewhere would help a lot! By the way: many thanks for this nice tool Tim!

**Comment by tgvaughan** [comment]
Hi Stephane!  Wow, I think you're the only person using IcyLog -  I'm amazed it still works!  I hope it continues to do so as long as you need it.  I've added in a few lines (commit bb34887) to display the filename in the tab - hopefully this helps. 

All the best,
Tim

**Comment by stephaneguindon** [comment]
Hi Tim. Still a big fan of IcyLog but the "polling" option does no longer seem to work on my side. It is probably due to a broken linux install on my side but I can't find a way to make this work again. Would you mind checking whether it could be an IcyLog problem? Cheers.
